# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=180, null=True)),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('fee', models.FloatField(blank=True, max_length=20, null=True)),
                ('camera', models.CharField(blank=True, choices=[('NIKON', 'Nikon'), ('ERSATZ', 'Ersatz'), ('NOTREAL', 'Notreal')], max_length=50, null=True)),
                ('services', models.CharField(blank=True, choices=[('BABIES', 'Babies'), ('WEDDINGS', 'Weddings'), ('ACTION', 'Action')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_styles', models.CharField(blank=True, choices=[('BW', 'B&W'), ('NOTBW', 'Not B&W'), ('FAKE', 'Fake')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
