# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='is_active',
        ),
    ]
