# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20171201_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(blank=True, choices=[('NIKON', 'Nikon'), ('ERSATZ', 'Ersatz'), ('NOTREAL', 'Notreal'), ('MINOLTA', 'Minolta'), ('CANNON', 'Cannon'), ('SONY', 'Sony')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=models.CharField(blank=True, choices=[('BW', 'B&W'), ('COLOR', 'Color'), ('FAKE', 'Fake')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=models.CharField(blank=True, choices=[('BABIES', 'Babies'), ('WEDDINGS', 'Weddings'), ('ACTION', 'Action'), ('NATURE', 'Nature'), ('PORTRAIT', 'Portrait'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
