# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20171203_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
