# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171204_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
    ]
